name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Conrad Großer <grosserconrad@gmail.com>

inputs:
  commit_message:
    description: Commit message, will be ignored if used with same_commit
    required: false
    default: "Prettified Code!"
  same_commit:
    description: Update the current commit instead of creating a new one
    required: false
    default: false
  commit_options:
    description: Commit options
    required: false
  push_options:
    description: Git push options
    required: false
  file_pattern:
    description: File pattern used for `git add`, can't be used with only_changed!
    required: false
    default: "*"
  prettier_options:
    description: Options for the `prettier` command
    required: false
    default: "--write **/*.js"
  dry:
    description: Running the script in dry mode just shows whether there are files that should be prettified or not
    required: false
    default: false
  prettier_version:
    description: Specific version of prettier (by default just use the latest version)
    required: false
    default: false
  only_changed:
    description: Only prettify files changed in the last commit, can't be used with file_pattern!
    required: false
    default: false
  prettier_plugins:
    description: Install Prettier plugins, i.e. `@prettier/plugin-php @prettier/plugin-other`
    required: false
    default: ''
  github_token:
    description: GitHub Token or PAT token used to authenticate against a repository
    required: false
    default: ${{ github.token }}


runs:
  using: "composite"
  steps:
    - name: Prettify code!
      shell: bash
      run: >-
        PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH
        ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        INPUT_SAME_COMMIT: ${{ inputs.same_commit }}
        INPUT_COMMIT_OPTIONS: ${{ inputs.commit_options }}
        INPUT_FILE_PATTERN: ${{ inputs.file_pattern }}
        INPUT_PRETTIER_OPTIONS: ${{ inputs.prettier_options }}
        INPUT_DRY: ${{ inputs.dry }}
        INPUT_PRETTIER_VERSION: ${{ inputs.prettier_version }}
        INPUT_ONLY_CHANGED: ${{ inputs.only_changed }}
        INPUT_PRETTIER_PLUGINS: ${{ inputs.prettier_plugins }}

branding:
  icon: "award"
  color: "green"
